redis_collections/dicts.py, tests/test_dicts.py
If you store any false value, such as `None`, `''` (empty string), `0` (int zero) and so on... then get() will return the default value instead of your stored false value.
New test case to demonstrate problem, and a simple fix.
=> Dict.get() with default on key holding a false value

redis_collections/__init__.py
This PR sets the version to 0.1.8.
I missed this before tagging a few minutes ago; my mistake.
=> Version bump to 0.1.8

.travis.yml, docs/conf.py, docs/index.rst, redis_collections/__init__.py, redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, requirements.txt, setup.cfg, setup.py, tests/base.py, tests/test_dicts.py, tests/test_lists.py, tests/test_sets.py
This PR builds upon the ideas in #22 and introduces partial support for Python 3. I'm not ready to consider Python 3 "well-supported" quite yet, as #25 (keys are coerced to strings) is more visible on Python 3.
Notes:
* I went ahead and used `six` as the compatibility layer, rather than writing and testing a custom compatibility layer.
* I've defensively added `__future__` imports for Python 2 to try to keep behaviors between the major versions as similar as possible (I don't think they're doing much work in practice)
* I've made some style changes as recommended by [flake8](http://flake8.pycqa.org/en/latest/). I'm not enforcing flake8-correctness in Travis yet, but probably will eventually.
* Keys get coerced to unicode strings instead of byte strings now. This doesn't mean much on …
=> Partial Python 3 support

docs/index.rst, redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, tests/test_dicts.py
Re: #25, this PR makes fairly drastic changes to the `Dict` and `Counter` classes in `redis_collections.dicts`. The biggest change involves how keys and values are stored in Redis:
* __Before__: A string-ified version of the key is set as the Redis field; a pickled version of the value is set as the Redis value
* __After__: A string-ified version of the `hash(key)` is set as the field; a pickled version of a `dict` mapping the key to the value is set as the Redis value
---
Also in this PR:
* __Custom serialization__: I've removed the ability to set the "pickler" during `Dict` class initialization for simplicity. Custom serialization can be achieved by overriding the `_pickle` and `_unpickle` methods (I may rename those to `_serialize` and `_deserialize`).
* __Counter compatibility__: I've …
=> Allow for non-string keys in Dict classes

.coveragerc, docs/index.rst, redis_collections/__init__.py, redis_collections/dicts.py, tests/test_dicts.py
Re: #26 and #9, this PR:
* Adds an optional local cache for use when storing mutable objects as `Dict` (and subclass) values
* Adds a Redis-backed `DefaultDict` class
---
__Local cache for mutable values__: See [this comment in issue 26](https://github.com/honzajavorek/redis-collections/issues/26#issuecomment-236079380) for why this cache is needed to support storing things like `dict`, `set`, and `list`.
Until you `sync`, changes to mutable values will not be stored in Redis:
```python
>>> D = Dict({'key': [1, 2]}, writeback=True)
>>> D['key'].append(3)
>>> D['key']  # Read from local cache
0: [1, 2, 3]
>>> D._data()['key']  # Read from Redis - not synced
1: [1, 2]
>>> D.sync()
>>> D._data()['key']  # Read from Redis - synced
2: [1, 2, 3]
```
You may also use a context manager to sync …
=> Local caching for mutable values B/W DefaultDict

redis_collections/lists.py, tests/test_lists.py, tests/test_sets.py
Re: #28, this augments the tests for `List` and `Set` such that most operations are also tested against `list` and `set`. (This is already done this for most of the `Dict` operations)
This revealed some problems with list slicing, in particular when the slice's `start` and `stop` were equal (should return an empty list) and when all three of `start`, `stop`, and `step` are not `None` (`L[i:j:k] != L[i:j][::k]` in many cases).
=> Python tests B/W List slicing fixes

.travis.yml, README.rst
This PR adds test coverage tracking with Coveralls.io - see first build's data [here](https://coveralls.io/builds/7322056). This will help point out where tests might be helpful, a la #28.
=> Add coveralls testing

redis_collections/dicts.py, redis_collections/lists.py, tests/test_lists.py
Re: #52, this PR adds the `writeback` and `sync` methods to `List`, plus context manager support.
This was a bit trickier than it was with `Dict`, due to index management.
```python
>>> from redis_collections import List
... 
... with List() as L:
...     L.append(set())
...     L[0].add(1)
... 
... print(list(L))
[{1}]
```
=> Add writeback and sync for List

setup.py
`README.rst` has some Unicode in it so on systems that have a preferred encoding of ascii installation fails with a `UnicodeDecodeError`. This specifies the encoding to be utf-8.
=> Specify encoding since README.rst has unicode in it

redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, tests/test_lists.py
Re: #55 and #56, this PR:
* Adds support for the to-be-implemented features in `List`
* Changes slicing and addition to return Python `list`s instead of Redis-backed `List`s.
* Reduces number of race conditions for list operations
* Increases test coverage for `lists.py` significantly
This is for the 0.3.0 release (see #59). I'll probably squash the commits here together before merging.
=> List improvements

redis_collections/__init__.py
This PR bumps the version number such that the fix in #57 can be released to PyPI.
=> Version bump to 0.2.1

redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, tests/test_sets.py
Re: #56 (return Python objects for non "update" methods) and #49 (things allowed in Redis-backed `Set`s that aren't allowed in Python `set`s), this PR makes significant changes to the `Set` class.
---
__Numeric key changes__: As [the issue](https://github.com/honzajavorek/redis-collections/issues/49) describes, previously there were surprises like this for using `Set`s with numeric keys: 
```python
... redis_set, python_set = Set(), set()
... for x in [1, 1.0, complex(1, 0), Fraction(1, 1), Decimal(1.0)]:
...     redis_set.add(x)
...     python_set.add(x)
>>> list(redis_set)
[Fraction(1, 1), 1.0, Decimal('1'), 1, (1+0j)]
>>> list(python_set)
[1]
```
This PR changes things such that equal numeric types will be serialized to the same values a la [Python's `hash` …
=> Set changes

redis_collections/base.py, redis_collections/dicts.py, redis_collections/sets.py, tests/test_dicts.py
Re: #56 (return Python objects for non "update" methods) and #58 (can't access a `Dict` from different processes in Python 3.3+), this PR makes changes to the `Dict` classes.
---
__Numeric and basestring key changes__: The solution from #61 for sets is adopted for `Dict`s. See [that PR](https://github.com/honzajavorek/redis-collections/pull/61#issue-171307493) for details and caveats.
This has the added benefit of making `__len__` fast for `Dicts` again - the number of items stored matches the number of hash fields. It also simplifies several methods.
---
__Counter operator methods return collections.Counter objects__: Per #56, addition, subtraction, intersection, union, etc. now return Python objects instead of Redis ones whose key cannot be controlled.
---
This is for 0.3.0 - see #59.
=> Fix Dict hashing, return collections.Counter for Counter operator methods

docs/index.rst, redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, setup.py, tests/test_dicts.py, tests/test_lists.py, tests/test_sets.py
Re: #17, this PR fixes a problem with using multiple Redis servers (or DBs).
---
Before this would raise an exception:
```python
>>> list_1 = List((1, 2, 3), redis=StrictRedis(db=0))
>>> list_2 = List((4, 5, 6), redis=StrictRedis(db=1))
>>> list_1.extend(list_2)
```
Now it gives the right result:
```
>>> list_1
<redis_collections.List at f55b1b39d6444ec6930bfd51eec93329 [1, 2, 3, 4, 5, 6]>
```
When dealing with two `RedisCollection` objects, the `_same_redis` method checks the (1) host, (2) port, (3) database number to determine whether operations can be done in Redis. If one of those doesn't match then the collections fall back to doing the operations in Python. This supersedes the `same_types` function.
---
This PR also cleans up some now-unused methods in the base class (e.g. …
=> Don't assume all collections stored on same Redis server B/W Clean up base class

redis_collections/dicts.py, redis_collections/lists.py, tests/test_dicts.py, tests/test_lists.py, tests/test_sets.py
Re: #68, this PR ensures testing for `__eq__` for the various collections and fixes up a race condition when comparing two Redis collections.
There is probably some more work to be done here. There is [discussion now in python-ideas](https://groups.google.com/forum/#!topic/python-ideas/wzMHaloezds) about how classes that inherit from `collections.abc.Sequence` should behave w.r.t equality testing, but for now I'll settle for fixing race conditions and unit testing.
This is for 0.3.0 - see #59.
=> Equality testing

README.rst
This PR changes the badge on the front-page README such that experiments on other branches don't cause it to show the build as failing.
=> Travis badge point to master

setup.py
Re: #39, our setup.py file currently reads in the entire license file, rather than naming the type of license.
[PyPA](http://python-packaging-user-guide.readthedocs.io/distributing/#license) recommends naming the type, so this PR changes setup.py to do that.
=> Use license type in setup.py

.travis.yml, setup.cfg
Re: #39, this PR changes the Travis CI configuration to build a ["universal" wheel](http://python-packaging-user-guide.readthedocs.io/distributing/#universal-wheels).
This applies because we're:
* Pure Python (i.e. no C extensions)
* Compatible with Python 2 and Python 3 without changes (i.e. no 2to3)
=> Build universal wheels

docs/index.rst, redis_collections/base.py, redis_collections/sets.py, tests/test_sets.py
Re: #74, this PR:
* Adds support for the `k` argument in `Set.random_sample` when the Redis server version is < 2.6.0
* Documents the Redis version support policy described in the issue
=> Set.random_sample for Redis < 2.6.0

README.rst, docs/index.rst, redis_collections/__init__.py, redis_collections/syncable.py, tests/test_syncable.py
Re: #79, this PR introduces a slate of "sync-able" collections, which allow you to work with Python `dict`s, `list`s, `set`s, etc. at normal speed (that is, without the slowness associated with sending to and receiving from Redis), but easily synchronize those collections to Redis.
---
__Usage__: Using a `with` block will automatically write changes to Redis
```python
>>> with SyncableDict() as D:
...     D['one'] = 1
...
>>> D  # Contents are available locally and are stored in Redis
{'one': 1}
>>> D['two'] = 2  # Changes are available locally, but not in Redis...
>>> D.sync()  # ...until sync is called.
```
You can attach to an earlier collection as well:
```python
>>> D.key
'f4a78a6faacb4d8e97829f9888ac6740'
>>> E = SyncableDict(key='f4a78a6faacb4d8e97829f9888ac6740')
>>> E
{'one': 1, …
```
=> Sync-able collections

docs/index.rst, redis_collections/base.py
See #83 for the motivation. This at least solves the issue for the test case:
```python
>>> from redis_collections import Set
... s = Set()
... key = (1, u'foo')
... s.add((1, u'foo'))
>>> (1, u'foo') in s
0: True
>>> key in s
1: True
```
`Set` and `Dict` on Python 2 should now behave better; no change for Python 3.
=> Switch from cPickle to pickle on Python 2

redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, redis_collections/sortedsets.py, redis_collections/syncable.py
In ca30e7dcdb457432ac1f9fdc745c0da13bd00785, @icecrime pointed out a potential pitfall with using the `thing = thing or get_thing()` idiom. This is incorrect to use for determining whether to use a redis-py `pipeline` instance or not, since the pipeline can evaluate to `False`. This PR removes that idiom from the various collections.
The base for this PR is #86 to avoid merge conflicts.
=> Test for pipe properly

redis_collections/syncable.py, tests/test_syncable.py
This PR fixes a bug with `SyncableDict` and `SyncableDefaultDict` - after deleting a key from a collection that's been synchronized, it should not stay around in Redis after the next synchronization. It also adds test for this behavior.
=> Clear syncable Dicts

docs/api.rst, docs/basic-usage.rst, docs/development.rst, docs/index.rst, docs/usage-notes.rst
This PR makes several changes to the documentation. See the results at [ReadTheDocs](http://redis-collections.readthedocs.io/en/docs-reorg/).
Summary:
* The contents of index.rst are split among multiple files now
* There is a new introduction and new "Installation and examples" section with more examples
* Several corrections to grammar and usage are made throughout
=> Re-organize docs

docs/changelog.rst, redis_collections/__init__.py, redis_collections/lists.py, tests/test_lists.py
This PR fixes a bug with `List.__eq__`. That method should check the lengths of the two lists, but doesn't, meaning that two lists like `[0, 1, 2]` and `[0, 1, 2, 3]` will compare as equal.
I will release this version to PyPI shortly.
=> 0.3.2 release for List equality testing bug fix

README.rst
This PR changes README.rst to have a reference to the various collections, consistent with the newly-reorganized docs (#89).
=> Add more information to GitHub README

redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, tests/test_dicts.py, tests/test_lists.py, tests/test_sets.py
This PR brings in the fix from #91 (``List`` equality testing bug) and raises test coverage to [100%](https://coveralls.io/builds/8043327).
Most of the missing tests were related to mixing standard collection types (e.g. update a `Dict` with a `List`). I will leave some comments about non-test changes.
=> Test coverage update

docs/api.rst, docs/conf.py, docs/development.rst, docs/usage-notes.rst, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, redis_collections/sortedsets.py, redis_collections/syncable.py
This PR makes several changes to the API documentation. See the results at [ReadTheDocs](http://redis-collections.readthedocs.io/en/api-doc-updates/api.html). Changes are mainly focused on improving clarity, spelling, and formatting.
=> Updates to API Documentation

README.rst, redis_collections/__init__.py, redis_collections/lists.py, redis_collections/syncable.py, tests/test_lists.py, tests/test_syncable.py
This PR adds `SyncableDeque`. Now each of the standard "auto-sync to Redis" collections has a corresponding "manual-sync to Redis" collection.
I think this will be the last change before version 0.4.0.
=> Syncable Deque

docs/changelog.rst, redis_collections/__init__.py
This PR bumps the version to 0.4.0 and updates the changelog with information about new things. I'll spot-check the docs again and release this to PyPI in a day or so.
=> Update changelog for 0.4.0

setup.py
This PR makes the `keywords` argument to `setup.py`'s `setup` a list instead of a string. I think the [docs](https://packaging.python.org/distributing/#keywords) are wrong for that... (see [here](https://pypi.python.org/pypi/redis-collections/0.4.0)).
=> Make setup.py keywords a list

redis_collections/dicts.py, redis_collections/sets.py, redis_collections/sortedsets.py, tests/test_dicts.py, tests/test_sets.py, tests/test_sortedsets.py
Re: #75, this PR adds support for the Redis SCAN commands on Hashes, Sets, and Sorted Sets.
As the Redis docs [note](http://redis.io/commands/scan#scan-guarantees):
> A given element may be returned multiple times. It is up to the application to handle the case of duplicated elements, for example only using the returned elements in order to perform operations that are safe when re-applied multiple times.
There's no good workaround for this, so I've added new scan methods instead of replacing e.g. `iteritems`.
This PR uses the [scan iterators](https://github.com/andymccurdy/redis-py#scan-iterators) from the redis-py package.
```python
>>> from redis_collections import Dict
... 
... D = Dict((x, str(x)) for x in range(1000))
... 
... for k, v in D.scan_items():
...     print(k, v, sep='\t') …
```
=> Implement SCAN for hashes, sets, and sorted sets

docs/usage-notes.rst, redis_collections/base.py, setup.cfg, tests/test_lists.py, tests/test_syncable.py
This PR adds a `pickle_protocol` argument to the `RedisCollection` class's constructor. It changes the default protocol from 0 to 2 on Python 2.7 and from `DEFAULT_PROTOCOL` to `HIGHEST_PROTOCOL` on Python 3.x.
The docs are also updated to recommend against using multiple Python versions to access a Redis collection.
This will be released as 0.5.x instead of 0.4.x, since currently Python 3.3 and 3.4+ would both be using protocol version 3.
=> Add pickle_protocol argument to base class

redis_collections/base.py
The `RedisCollection._same_redis` method checks the `connection_pool.connection_kwargs` dict of the `StrictRedis` instance to determine whether two collections are using the same Redis server.
That dict has `host` and `port` entries when Redis is listening on a network socket, but a `path` entry when Redis is using a domain socket.
This PR changes  `_same_redis` to support the `path` entry.
```python
{'db': 0,
'decode_responses': False,
'encoding': 'utf-8',
'encoding_errors': 'strict',
'password': None,
'path': '/tmp/tmp5qhsjU/redis.socket',
'retry_on_timeout': False,
'socket_timeout': None}
```
=> Add support for Unix sockets in _same_redis

redis_collections/dicts.py
This PR reduces memory usage a bit during the `Dict.update` operation.
Before: A `data` dict would be created for the items to be inserted, and then a dict of pickled data would be created from that.
After: The pickled dict is filled by popping items out of the `data` dict, to avoid having two copies at once. Due to Python internals this isn't quite the memory savings you would think, but it's something.
[redis-py](https://redis-py.readthedocs.io/en/latest/_modules/redis/client.html#StrictRedis.hmset) makes more copies of the data, so there is probably some more efficiency that could be had here.
=> Save some memory when doing Dict.update

setup.py
This PR adds `six` to `setup.py`. It seems that excluding it was an oversight...
=> Add six to requirements

docs/changelog.rst
Re: https://github.com/honzajavorek/redis-collections/issues/112, this PR adds a note on incompatibility between versions 0.4.x and 0.5.x.
As noted [here](https://github.com/honzajavorek/redis-collections/issues/112#issuecomment-443392441), you can connect to a collection created by 0.4.x by specifying which pickle protocol version to use.
=>  Note breaking changes re: pickling 

.travis.yml
This PR changes the `.travis.yml` configuration - see [this blog post](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
=> Remove sudo:false from .travis.yml

docs/api.rst, docs/changelog.rst, redis_collections/__init__.py, redis_collections/base.py, redis_collections/sets.py, redis_collections/sortedsets.py, setup.py, tests/test_lists.py, tests/test_sortedsets.py
Re: Issue https://github.com/honzajavorek/redis-collections/issues/104, this PR adds `GeoDB`, a new interface for the Redis GEO commands. See the [tests](https://github.com/honzajavorek/redis-collections/compare/geodb?expand=1#diff-12ae233241f404ad5e7ceaf1b6bbd53cR251) for example uses.
Also:
* This library now requires `redis-py` 3.1.0
* The version will be 0.6.0 after this merge
=> Add GeoDB class

docs/changelog.rst, redis_collections/__init__.py, redis_collections/sets.py, redis_collections/sortedsets.py, tests/test_sets.py
This PR gathers together changes for the 0.6.0 release.
Of note:
* We now require `redis-py` 3.1.0+
* We now require Redis server 2.8.0+
* The `GeoDB` collection is now available
=> Release 0.6.0

.gitignore, .travis.yml, docs/usage-notes.rst, redis_collections/__init__.py, redis_collections/base.py, redis_collections/dicts.py, redis_collections/lists.py, redis_collections/sets.py, redis_collections/sortedsets.py, redis_collections/syncable.py, requirements.txt, setup.py, tests/base.py, tests/test_dicts.py, tests/test_lists.py, tests/test_sets.py, tests/test_sortedsets.py, tests/test_syncable.py
This PR removes the reliance on `six` and the Python 2 compatibility code. The next release will support Python 3.4+.
=> Drop Python 2.7 support

docs/changelog.rst, redis_collections/__init__.py
This PR bumps the version number and adds a note about Python 3.4+ compatibility.
=> 0.8.0 release

.travis.yml, docs/changelog.rst, redis_collections/__init__.py, redis_collections/base.py, redis_collections/dicts.py
This PR adds a wrapper around the `hmset` method, which has been [deprecated](https://github.com/andymccurdy/redis-py/blob/32a58406b2769f423170142e21d164c863697ebc/CHANGES#L24-L25) in `redis-py` version 3.5.0.
This library will continue to support `redis-py` 3.0.0 and above; this update is to avoid triggering the `DeprecationWarning` associated with the `hmset` change.
=>  Avoid DeprecationWarning for redis-py 3.5.x 

.travis.yml, redis_collections/dicts.py, tests/test_dicts.py
Re: #129, this PR adds `|` and `|=` operator support for `Dict` instances, a la Python 3.9.
=> Python 3.9-style support for | and |= for Dict

LICENSE, README.rst
In my last job in Oracle, I had an unparalleled, "joyful" opportunity to learn many details about licensing and copyrights. I'm still no lawyer, but based on that experience, I'm proposing the following changes as I think they better reflect the post-2016 reality and it allows me to put all my new knowledge to use!
- Given there's no SLA (Software License Agreement) where contributors grant their rights to the project owner, everyone who contributed to the project is still owner of their code, and they offer it under the ISC license.
- That means anyone who contributed to the project should theoretically get mentioned in copyrights, but in practice this is usually done in a way that only the main author is mentioned in full name and then "and contributors" is appended. So I did that.
- I …
=> Update the license

docs/usage-notes.rst
This PR removes an outdated reference to Python 2, and in doing so, allows me to test the RTD after switching over to using the `redis-collections` organization.
=> Remove reference to Python 2

.gitignore, docs/changelog.rst, redis_collections/__init__.py, redis_collections/base.py, tests/base.py, tests/test_dicts.py, tests/test_sortedsets.py
Re: https://github.com/redis-collections/redis-collections/issues/141, this PR:
* Adds an `hmset_command` keyword argument to the collections
* By default this is `'hmset'`, which should work on all current versions of Redis server and `redis-py`
* It can be set to `'hset'` if `redis-py`'s `DeprecationWarning` is a problem
In the next release I will remove support for versions of Redis server below 4.0.0. When `redis-py` drops the `hmset` command I will remove the keyword argument.
=> Fix HSET on Redis Server < 4.0.0

.github/workflows/python-app.yml, docs/changelog.rst, redis_collections/__init__.py, redis_collections/syncable.py, tests/test_syncable.py
Re: https://github.com/redis-collections/redis-collections/issues/144, this PR updates the `Syncable` collections such that their `sync` operation is atomic. The method here is: copy all local data to Redis using a new key, then rename the old key to the new key.
=> Make Syncable collections sync atomically

.github/workflows/python-app.yml, docs/changelog.rst, docs/requirements.txt, redis_collections/__init__.py, redis_collections/base.py, redis_collections/sortedsets.py, setup.py, tests/test_sets.py
This PR incorporates the change @lionelnicolas suggested in #147 as well as some others:
* Python version support: since 3.6 is EOL, Python 3.7 is now the lowest supported version
* Redis-py version support: since 4.1/x is out, 3.5.x is now the lowest support version.
I'll release this to PyPI shortly.
=> Version 0.11.0

redis_collections/syncable.py
This PR updates `LRUDict` such that it only copies items from its local cache during the `sync` operation.
Thanks to @beckermr for the suggestion.
Closes #151
=> LRUDict: copy the local cache only when using sync
